import type { Metadata } from "next";
import { Questrial, Poppins, Luckiest_Guy } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/ui/Navbar";
import { Providers } from "./Providers";

const questrial = Questrial({
  variable: "--font-questrial",
  subsets: ["latin"],
  weight: ["400"]
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "600"]
});

const luckiestGuy = Luckiest_Guy({
  variable: "--font-luckiest-guy",
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata: Metadata = {
  title: "! - VC2",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <NavBar />
          <div className="max-width-container">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
